WITH SALE AS (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= '2022-03-01'
      AND SALES_DATE < '2022-04-01'
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= '2022-03-01'
      AND SALES_DATE < '2022-04-01'
)
SELECT *
FROM SALE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID


